import { GoogleGenAI, Type, Schema } from "@google/genai";
import { WordChallenge, EvaluationResult } from "../types";

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
const MODEL_NAME = "gemini-3-flash-preview";

/**
 * Expanded WORD_BANK to 500 words for 10-12 year olds.
 * Includes Adjectives, Verbs, and Nouns with definitions and synonyms.
 */
const WORD_BANK: WordChallenge[] = [
  // --- ADJECTIVES (1-170) ---
  { word: "Reluctant", partOfSpeech: "adjective", definition: "Not wanting to do something.", synonyms: ["hesitant", "unwilling"] },
  { word: "Vivid", partOfSpeech: "adjective", definition: "Very bright or clear.", synonyms: ["bright", "colorful", "clear"] },
  { word: "Diligent", partOfSpeech: "adjective", definition: "Working hard and carefully.", synonyms: ["hardworking", "careful"] },
  { word: "Peculiar", partOfSpeech: "adjective", definition: "Strange or unusual.", synonyms: ["strange", "odd", "weird"] },
  { word: "Authentic", partOfSpeech: "adjective", definition: "Real and true; not fake.", synonyms: ["real", "genuine"] },
  { word: "Solitary", partOfSpeech: "adjective", definition: "Spending time alone.", synonyms: ["alone", "lonely"] },
  { word: "Tremendous", partOfSpeech: "adjective", definition: "Very large or great.", synonyms: ["huge", "giant", "great"] },
  { word: "Resilient", partOfSpeech: "adjective", definition: "Able to bounce back from hard times.", synonyms: ["strong", "tough"] },
  { word: "Optimistic", partOfSpeech: "adjective", definition: "Expecting good things to happen.", synonyms: ["positive", "hopeful"] },
  { word: "Ancient", partOfSpeech: "adjective", definition: "Very, very old.", synonyms: ["old", "antique"] },
  { word: "Precise", partOfSpeech: "adjective", definition: "Exact and correct.", synonyms: ["exact", "accurate"] },
  { word: "Unique", partOfSpeech: "adjective", definition: "Being the only one of its kind.", synonyms: ["special", "one of a kind"] },
  { word: "Weary", partOfSpeech: "adjective", definition: "Very tired.", synonyms: ["tired", "exhausted"] },
  { word: "Curious", partOfSpeech: "adjective", definition: "Wanting to learn or know more.", synonyms: ["interested", "inquisitive"] },
  { word: "Humble", partOfSpeech: "adjective", definition: "Not thinking you are better than others.", synonyms: ["modest", "simple"] },
  { word: "Rapid", partOfSpeech: "adjective", definition: "Happening very quickly.", synonyms: ["fast", "quick"] },
  { word: "Abundant", partOfSpeech: "adjective", definition: "Having plenty of something.", synonyms: ["plentiful", "ample"] },
  { word: "Adversarial", partOfSpeech: "adjective", definition: "Acting like an enemy.", synonyms: ["hostile", "opposing"] },
  { word: "Ambitious", partOfSpeech: "adjective", definition: "Having a strong desire to succeed.", synonyms: ["driven", "aspiring"] },
  { word: "Amiable", partOfSpeech: "adjective", definition: "Friendly and pleasant.", synonyms: ["friendly", "kind"] },
  { word: "Anxious", partOfSpeech: "adjective", definition: "Feeling worried or nervous.", synonyms: ["worried", "uneasy"] },
  { word: "Apprehensive", partOfSpeech: "adjective", definition: "Fearful that something bad will happen.", synonyms: ["nervous", "worried"] },
  { word: "Arid", partOfSpeech: "adjective", definition: "Very dry, like a desert.", synonyms: ["dry", "parched"] },
  { word: "Articulate", partOfSpeech: "adjective", definition: "Able to speak clearly and effectively.", synonyms: ["clear", "eloquent"] },
  { word: "Astonishing", partOfSpeech: "adjective", definition: "Extremely surprising.", synonyms: ["amazing", "surprising"] },
  { word: "Belligerent", partOfSpeech: "adjective", definition: "Wishing to fight or argue.", synonyms: ["aggressive", "hostile"] },
  { word: "Benevolent", partOfSpeech: "adjective", definition: "Kind and helpful.", synonyms: ["kind", "generous"] },
  { word: "Boisterous", partOfSpeech: "adjective", definition: "Noisy, energetic, and cheerful.", synonyms: ["lively", "rowdy"] },
  { word: "Brilliant", partOfSpeech: "adjective", definition: "Extremely clever or bright.", synonyms: ["intelligent", "bright"] },
  { word: "Calamitous", partOfSpeech: "adjective", definition: "Causing great damage or distress.", synonyms: ["disastrous", "tragic"] },
  { word: "Candid", partOfSpeech: "adjective", definition: "Truthful and straightforward.", synonyms: ["honest", "frank"] },
  { word: "Capable", partOfSpeech: "adjective", definition: "Having the ability to do something.", synonyms: ["able", "skilled"] },
  { word: "Captivating", partOfSpeech: "adjective", definition: "Holding your attention completely.", synonyms: ["charming", "fascinating"] },
  { word: "Cautious", partOfSpeech: "adjective", definition: "Taking care to avoid danger.", synonyms: ["careful", "wary"] },
  { word: "Clumsy", partOfSpeech: "adjective", definition: "Lacking grace in movement.", synonyms: ["awkward", "ungainly"] },
  { word: "Coherent", partOfSpeech: "adjective", definition: "Logical and consistent.", synonyms: ["clear", "rational"] },
  { word: "Compassionate", partOfSpeech: "adjective", definition: "Feeling or showing sympathy for others.", synonyms: ["caring", "kind"] },
  { word: "Complex", partOfSpeech: "adjective", definition: "Consisting of many different parts.", synonyms: ["complicated", "intricate"] },
  { word: "Confusing", partOfSpeech: "adjective", definition: "Difficult to understand.", synonyms: ["puzzling", "baffling"] },
  { word: "Conspicuous", partOfSpeech: "adjective", definition: "Easily seen or noticed.", synonyms: ["noticeable", "obvious"] },
  { word: "Courageous", partOfSpeech: "adjective", definition: "Being brave in the face of fear.", synonyms: ["brave", "valiant"] },
  { word: "Cunning", partOfSpeech: "adjective", definition: "Skillful at tricking others.", synonyms: ["sly", "clever"] },
  { word: "Dauntless", partOfSpeech: "adjective", definition: "Showing fearlessness and determination.", synonyms: ["fearless", "bold"] },
  { word: "Decisive", partOfSpeech: "adjective", definition: "Able to make choices quickly and confidently.", synonyms: ["determined", "firm"] },
  { word: "Defiant", partOfSpeech: "adjective", definition: "Refusing to obey someone or something.", synonyms: ["rebellious", "disobedient"] },
  { word: "Delicate", partOfSpeech: "adjective", definition: "Easily broken or damaged.", synonyms: ["fragile", "dainty"] },
  { word: "Desolate", partOfSpeech: "adjective", definition: "Empty and without people.", synonyms: ["lonely", "barren"] },
  { word: "Detailed", partOfSpeech: "adjective", definition: "Including many small items of info.", synonyms: ["thorough", "complete"] },
  { word: "Determined", partOfSpeech: "adjective", definition: "Not letting anything stop you.", synonyms: ["resolute", "firm"] },
  { word: "Devout", partOfSpeech: "adjective", definition: "Having deep religious feelings.", synonyms: ["pious", "sincere"] },
  { word: "Diminutive", partOfSpeech: "adjective", definition: "Extremely small.", synonyms: ["tiny", "small"] },
  { word: "Discordant", partOfSpeech: "adjective", definition: "Harsh and jarring because of lack of harmony.", synonyms: ["clashing", "harsh"] },
  { word: "Discreet", partOfSpeech: "adjective", definition: "Careful not to attract attention.", synonyms: ["careful", "subtle"] },
  { word: "Distant", partOfSpeech: "adjective", definition: "Far away in space or time.", synonyms: ["far", "remote"] },
  { word: "Distinct", partOfSpeech: "adjective", definition: "Clearly different from others.", synonyms: ["clear", "different"] },
  { word: "Diverse", partOfSpeech: "adjective", definition: "Showing a great deal of variety.", synonyms: ["varied", "different"] },
  { word: "Dreadful", partOfSpeech: "adjective", definition: "Causing great fear or sadness.", synonyms: ["terrible", "awful"] },
  { word: "Drastic", partOfSpeech: "adjective", definition: "Likely to have a strong or far-reaching effect.", synonyms: ["extreme", "severe"] },
  { word: "Durable", partOfSpeech: "adjective", definition: "Able to last a long time.", synonyms: ["strong", "tough"] },
  { word: "Eager", partOfSpeech: "adjective", definition: "Wanting to do something very much.", synonyms: ["excited", "keen"] },
  { word: "Earnest", partOfSpeech: "adjective", definition: "Serious and sincere.", synonyms: ["serious", "sincere"] },
  { word: "Eccentric", partOfSpeech: "adjective", definition: "Unconventional and slightly strange.", synonyms: ["odd", "quirky"] },
  { word: "Elated", partOfSpeech: "adjective", definition: "Extremely happy and excited.", synonyms: ["overjoyed", "thrilled"] },
  { word: "Eloquent", partOfSpeech: "adjective", definition: "Fluent or persuasive in speaking.", synonyms: ["expressive", "fluent"] },
  { word: "Elusive", partOfSpeech: "adjective", definition: "Difficult to find or catch.", synonyms: ["slippery", "tricky"] },
  { word: "Eminent", partOfSpeech: "adjective", definition: "Famous and respected.", synonyms: ["noted", "famous"] },
  { word: "Enormous", partOfSpeech: "adjective", definition: "Very large in size.", synonyms: ["huge", "giant"] },
  { word: "Enthusiastic", partOfSpeech: "adjective", definition: "Showing intense interest.", synonyms: ["excited", "eager"] },
  { word: "Erratic", partOfSpeech: "adjective", definition: "Not regular or consistent.", synonyms: ["unpredictable", "unstable"] },
  { word: "Exaggerated", partOfSpeech: "adjective", definition: "Better or worse than it really is.", synonyms: ["inflated", "overstated"] },
  { word: "Exceptional", partOfSpeech: "adjective", definition: "Unusually good.", synonyms: ["excellent", "outstanding"] },
  { word: "Exotic", partOfSpeech: "adjective", definition: "Originating in a distant foreign country.", synonyms: ["foreign", "unusual"] },
  { word: "Extravagant", partOfSpeech: "adjective", definition: "Lacking restraint in spending money.", synonyms: ["wasteful", "lavish"] },
  { word: "Exuberant", partOfSpeech: "adjective", definition: "Full of energy and excitement.", synonyms: ["lively", "energetic"] },
  { word: "Fabulous", partOfSpeech: "adjective", definition: "Extraordinarily good.", synonyms: ["wonderful", "great"] },
  { word: "Familiar", partOfSpeech: "adjective", definition: "Well known from being seen often.", synonyms: ["known", "common"] },
  { word: "Fanciful", partOfSpeech: "adjective", definition: "Existing only in the imagination.", synonyms: ["imaginary", "whimsical"] },
  { word: "Fearless", partOfSpeech: "adjective", definition: "Lacking fear.", synonyms: ["brave", "bold"] },
  { word: "Feeble", partOfSpeech: "adjective", definition: "Lacking physical strength.", synonyms: ["weak", "frail"] },
  { word: "Ferocious", partOfSpeech: "adjective", definition: "Savagely fierce or cruel.", synonyms: ["fierce", "wild"] },
  { word: "Fervent", partOfSpeech: "adjective", definition: "Having a passionate intensity.", synonyms: ["passionate", "intense"] },
  { word: "Festive", partOfSpeech: "adjective", definition: "Cheerful and jovial.", synonyms: ["merry", "jolly"] },
  { word: "Fickle", partOfSpeech: "adjective", definition: "Changing frequently.", synonyms: ["unpredictable", "variable"] },
  { word: "Fierce", partOfSpeech: "adjective", definition: "Powerful and aggressive.", synonyms: ["strong", "wild"] },
  { word: "Flawless", partOfSpeech: "adjective", definition: "Without any imperfections.", synonyms: ["perfect", "unblemished"] },
  { word: "Flexible", partOfSpeech: "adjective", definition: "Able to bend easily.", synonyms: ["pliable", "adaptable"] },
  { word: "Foolish", partOfSpeech: "adjective", definition: "Lacking good sense.", synonyms: ["silly", "unwise"] },
  { word: "Formal", partOfSpeech: "adjective", definition: "Done in accordance with rules.", synonyms: ["official", "proper"] },
  { word: "Fragile", partOfSpeech: "adjective", definition: "Easily broken.", synonyms: ["delicate", "weak"] },
  { word: "Frank", partOfSpeech: "adjective", definition: "Open and honest in expression.", synonyms: ["candid", "direct"] },
  { word: "Frantic", partOfSpeech: "adjective", definition: "Wild with fear or anxiety.", synonyms: ["panicked", "wild"] },
  { word: "Frequent", partOfSpeech: "adjective", definition: "Happening often.", synonyms: ["common", "repeated"] },
  { word: "Friendly", partOfSpeech: "adjective", definition: "Kind and pleasant.", synonyms: ["amiable", "kind"] },
  { word: "Fruitful", partOfSpeech: "adjective", definition: "Producing good results.", synonyms: ["productive", "useful"] },
  { word: "Furious", partOfSpeech: "adjective", definition: "Extremely angry.", synonyms: ["angry", "enraged"] },
  { word: "Futile", partOfSpeech: "adjective", definition: "Pointless or useless.", synonyms: ["useless", "vain"] },
  { word: "Gaudy", partOfSpeech: "adjective", definition: "Extravagantly bright or showy.", synonyms: ["flashy", "tasteless"] },
  { word: "Generous", partOfSpeech: "adjective", definition: "Showing a readiness to give.", synonyms: ["kind", "giving"] },
  { word: "Gentle", partOfSpeech: "adjective", definition: "Mild in temperament.", synonyms: ["kind", "soft"] },
  { word: "Genuine", partOfSpeech: "adjective", definition: "Truly what something is said to be.", synonyms: ["real", "authentic"] },
  { word: "Ghastly", partOfSpeech: "adjective", definition: "Causing great horror or fear.", synonyms: ["horrible", "terrible"] },
  { word: "Giant", partOfSpeech: "adjective", definition: "Of very great size.", synonyms: ["huge", "enormous"] },
  { word: "Giddy", partOfSpeech: "adjective", definition: "Feeling excited or light-headed.", synonyms: ["dizzy", "silly"] },
  { word: "Gifted", partOfSpeech: "adjective", definition: "Having natural talent.", synonyms: ["talented", "skilled"] },
  { word: "Gigantic", partOfSpeech: "adjective", definition: "Extremely large.", synonyms: ["huge", "massive"] },
  { word: "Gleaming", partOfSpeech: "adjective", definition: "Shining brightly.", synonyms: ["shiny", "bright"] },
  { word: "Glistening", partOfSpeech: "adjective", definition: "Shining with reflected light.", synonyms: ["shining", "sparkling"] },
  { word: "Gloomy", partOfSpeech: "adjective", definition: "Dark or poorly lit.", synonyms: ["dark", "sad"] },
  { word: "Glorious", partOfSpeech: "adjective", definition: "Having great beauty or splendor.", synonyms: ["magnificent", "wonderful"] },
  { word: "Graceful", partOfSpeech: "adjective", definition: "Showing elegance in movement.", synonyms: ["elegant", "fluid"] },
  { word: "Gracious", partOfSpeech: "adjective", definition: "Courteous and kind.", synonyms: ["polite", "kind"] },
  { word: "Grateful", partOfSpeech: "adjective", definition: "Feeling or showing thanks.", synonyms: ["thankful", "appreciative"] },
  { word: "Greedy", partOfSpeech: "adjective", definition: "Having an intense desire for wealth.", synonyms: ["selfish", "avaricious"] },
  { word: "Grievous", partOfSpeech: "adjective", definition: "Very severe or serious.", synonyms: ["serious", "grave"] },
  { word: "Grim", partOfSpeech: "adjective", definition: "Forbidding or uninviting.", synonyms: ["stern", "harsh"] },
  { word: "Grotesque", partOfSpeech: "adjective", definition: "Comically or repulsively ugly.", synonyms: ["bizarre", "ugly"] },
  { word: "Grueling", partOfSpeech: "adjective", definition: "Extremely tiring and demanding.", synonyms: ["exhausting", "tough"] },
  { word: "Gullible", partOfSpeech: "adjective", definition: "Easily persuaded to believe something.", synonyms: ["trusting", "naive"] },
  { word: "Habitual", partOfSpeech: "adjective", definition: "Done as a constant habit.", synonyms: ["regular", "constant"] },
  { word: "Handy", partOfSpeech: "adjective", definition: "Useful or convenient.", synonyms: ["useful", "helpful"] },
  { word: "Haphazard", partOfSpeech: "adjective", definition: "Lacking any obvious organization.", synonyms: ["random", "disorganized"] },
  { word: "Harsh", partOfSpeech: "adjective", definition: "Unpleasantly rough or jarring.", synonyms: ["cruel", "severe"] },
  { word: "Hasty", partOfSpeech: "adjective", definition: "Done with excessive speed.", synonyms: ["quick", "rushed"] },
  { word: "Healthy", partOfSpeech: "adjective", definition: "In good physical condition.", synonyms: ["fit", "well"] },
  { word: "Heated", partOfSpeech: "adjective", definition: "Showing strong feeling or anger.", synonyms: ["angry", "intense"] },
  { word: "Heavy", partOfSpeech: "adjective", definition: "Of great weight.", synonyms: ["weighty", "bulky"] },
  { word: "Helpful", partOfSpeech: "adjective", definition: "Giving or ready to give help.", synonyms: ["useful", "kind"] },
  { word: "Heroic", partOfSpeech: "adjective", definition: "Having the qualities of a hero.", synonyms: ["brave", "valiant"] },
  { word: "High", partOfSpeech: "adjective", definition: "Of great vertical extent.", synonyms: ["tall", "elevated"] },
  { word: "Hilarious", partOfSpeech: "adjective", definition: "Extremely funny.", synonyms: ["funny", "comical"] },
  { word: "Honest", partOfSpeech: "adjective", definition: "Free of deceit and untruthful.", synonyms: ["truthful", "sincere"] },
  { word: "Hopeful", partOfSpeech: "adjective", definition: "Feeling or inspiring optimism.", synonyms: ["optimistic", "positive"] },
  { word: "Horrible", partOfSpeech: "adjective", definition: "Causing horror.", synonyms: ["awful", "terrible"] },
  { word: "Hospitable", partOfSpeech: "adjective", definition: "Friendly to guests.", synonyms: ["welcoming", "friendly"] },
  { word: "Hostile", partOfSpeech: "adjective", definition: "Unfriendly and antagonistic.", synonyms: ["unfriendly", "aggressive"] },
  { word: "Huge", partOfSpeech: "adjective", definition: "Extremely large.", synonyms: ["enormous", "gigantic"] },
  { word: "Humane", partOfSpeech: "adjective", definition: "Having or showing compassion.", synonyms: ["kind", "caring"] },
  { word: "Humble", partOfSpeech: "adjective", definition: "Having a modest view of one's importance.", synonyms: ["modest", "simple"] },
  { word: "Humorous", partOfSpeech: "adjective", definition: "Causing laughter and amusement.", synonyms: ["funny", "witty"] },
  { word: "Hungry", partOfSpeech: "adjective", definition: "Feeling a need for food.", synonyms: ["famished", "starving"] },
  { word: "Hurried", partOfSpeech: "adjective", definition: "Done with great haste.", synonyms: ["rushed", "fast"] },
  { word: "Hurtful", partOfSpeech: "adjective", definition: "Causing emotional pain.", synonyms: ["painful", "cruel"] },
  { word: "Hysterical", partOfSpeech: "adjective", definition: "Deriving from extreme emotion.", synonyms: ["wild", "frantic"] },
  { word: "Icy", partOfSpeech: "adjective", definition: "Covered with or consisting of ice.", synonyms: ["cold", "frozen"] },
  { word: "Ideal", partOfSpeech: "adjective", definition: "Satisfying one's conception of what is perfect.", synonyms: ["perfect", "best"] },
  { word: "Identical", partOfSpeech: "adjective", definition: "Similar in every detail.", synonyms: ["same", "equal"] },
  { word: "Idle", partOfSpeech: "adjective", definition: "Not active or in use.", synonyms: ["inactive", "lazy"] },
  { word: "Ignorant", partOfSpeech: "adjective", definition: "Lacking knowledge or awareness.", synonyms: ["uninformed", "unaware"] },
  { word: "Ill", partOfSpeech: "adjective", definition: "Suffering from a disease or feeling unwell.", synonyms: ["sick", "unwell"] },
  { word: "Illegal", partOfSpeech: "adjective", definition: "Contrary to or forbidden by law.", synonyms: ["unlawful", "prohibited"] },
  { word: "Illustrious", partOfSpeech: "adjective", definition: "Well known and respected.", synonyms: ["famous", "eminent"] },
  { word: "Imaginary", partOfSpeech: "adjective", definition: "Existing only in the mind.", synonyms: ["fanciful", "fictional"] },
  { word: "Immaculate", partOfSpeech: "adjective", definition: "Perfectly clean and neat.", synonyms: ["spotless", "clean"] },
  { word: "Immense", partOfSpeech: "adjective", definition: "Extremely large or great.", synonyms: ["huge", "massive"] },
  { word: "Imminent", partOfSpeech: "adjective", definition: "About to happen.", synonyms: ["near", "approaching"] },
  { word: "Impartial", partOfSpeech: "adjective", definition: "Treating all rivals equally.", synonyms: ["fair", "neutral"] },
  { word: "Impatient", partOfSpeech: "adjective", definition: "Showing a tendency to be quickly irritated.", synonyms: ["restless", "eager"] },
  { word: "Imperfect", partOfSpeech: "adjective", definition: "Not perfect.", synonyms: ["flawed", "faulty"] },
  { word: "Impolite", partOfSpeech: "adjective", definition: "Not having good manners.", synonyms: ["rude", "discourteous"] },
  { word: "Important", partOfSpeech: "adjective", definition: "Of great value.", synonyms: ["significant", "crucial"] },
  { word: "Impossible", partOfSpeech: "adjective", definition: "Not able to occur.", synonyms: ["unattainable", "hopeless"] },
  { word: "Impressed", partOfSpeech: "adjective", definition: "Feeling admiration.", synonyms: ["admiring", "moved"] },
  { word: "Impressive", partOfSpeech: "adjective", definition: "Evoking admiration.", synonyms: ["grand", "splendid"] },
  { word: "Improper", partOfSpeech: "adjective", definition: "Not in accordance with accepted standards.", synonyms: ["wrong", "unsuitable"] },
  { word: "Improved", partOfSpeech: "adjective", definition: "Having become better.", synonyms: ["better", "enhanced"] },
  { word: "Inadequate", partOfSpeech: "adjective", definition: "Lacking the quality required.", synonyms: ["insufficient", "poor"] },
  { word: "Inappropriate", partOfSpeech: "adjective", definition: "Not suitable.", synonyms: ["unsuitable", "improper"] },
  { word: "Incapable", partOfSpeech: "adjective", definition: "Unable to do or achieve.", synonyms: ["unable", "unfit"] },
  { word: "Incidental", partOfSpeech: "adjective", definition: "Accompanying but not major.", synonyms: ["minor", "secondary"] },

  // --- VERBS (171-340) ---
  { word: "Ponder", partOfSpeech: "verb", definition: "To think carefully about something.", synonyms: ["think", "wonder", "consider"] },
  { word: "Bewilder", partOfSpeech: "verb", definition: "To confuse someone very much.", synonyms: ["confuse", "puzzle"] },
  { word: "Collaborate", partOfSpeech: "verb", definition: "To work together with others.", synonyms: ["team up", "cooperate"] },
  { word: "Emerge", partOfSpeech: "verb", definition: "To come out into view.", synonyms: ["appear", "come out"] },
  { word: "Inspire", partOfSpeech: "verb", definition: "To give someone a great idea or feeling.", synonyms: ["encourage", "motivate"] },
  { word: "Detect", partOfSpeech: "verb", definition: "To discover or notice something.", synonyms: ["find", "spot", "notice"] },
  { word: "Glimmer", partOfSpeech: "verb", definition: "To shine with a weak light.", synonyms: ["shine", "sparkle", "twinkle"] },
  { word: "Imitate", partOfSpeech: "verb", definition: "To copy what someone does.", synonyms: ["copy", "mimic"] },
  { word: "Marvel", partOfSpeech: "verb", definition: "To be filled with wonder or amazement.", synonyms: ["wonder", "admire"] },
  { word: "Orbit", partOfSpeech: "verb", definition: "To travel around a planet or star.", synonyms: ["circle", "revolve"] },
  { word: "Vanish", partOfSpeech: "verb", definition: "To disappear suddenly.", synonyms: ["disappear", "fade"] },
  { word: "Acknowledge", partOfSpeech: "verb", definition: "To accept that something exists.", synonyms: ["admit", "recognize"] },
  { word: "Acquire", partOfSpeech: "verb", definition: "To get or buy something.", synonyms: ["get", "obtain"] },
  { word: "Adapt", partOfSpeech: "verb", definition: "To change to suit a new situation.", synonyms: ["adjust", "modify"] },
  { word: "Analyze", partOfSpeech: "verb", definition: "To study something in detail.", synonyms: ["examine", "investigate"] },
  { word: "Anticipate", partOfSpeech: "verb", definition: "To expect or predict.", synonyms: ["expect", "foresee"] },
  { word: "Argue", partOfSpeech: "verb", definition: "To speak angrily with someone.", synonyms: ["quarrel", "fight"] },
  { word: "Assert", partOfSpeech: "verb", definition: "To state a fact or belief confidently.", synonyms: ["state", "declare"] },
  { word: "Avoid", partOfSpeech: "verb", definition: "To keep away from.", synonyms: ["shun", "escape"] },
  { word: "Barter", partOfSpeech: "verb", definition: "To trade goods for other goods.", synonyms: ["trade", "exchange"] },
  { word: "Belittle", partOfSpeech: "verb", definition: "To make something seem unimportant.", synonyms: ["dismiss", "disparage"] },
  { word: "Bellow", partOfSpeech: "verb", definition: "To shout in a loud deep voice.", synonyms: ["shout", "roar"] },
  { word: "Boast", partOfSpeech: "verb", definition: "To talk with excessive pride.", synonyms: ["brag", "show off"] },
  { word: "Captivate", partOfSpeech: "verb", definition: "To attract and hold interest.", synonyms: ["charm", "fascinate"] },
  { word: "Challenge", partOfSpeech: "verb", definition: "To invite someone to compete.", synonyms: ["dare", "test"] },
  { word: "Clarify", partOfSpeech: "verb", definition: "To make something clearer.", synonyms: ["explain", "simplify"] },
  { word: "Coax", partOfSpeech: "verb", definition: "To gently persuade someone.", synonyms: ["persuade", "wheedle"] },
  { word: "Commence", partOfSpeech: "verb", definition: "To begin or start.", synonyms: ["start", "begin"] },
  { word: "Compel", partOfSpeech: "verb", definition: "To force someone to do something.", synonyms: ["force", "require"] },
  { word: "Conclude", partOfSpeech: "verb", definition: "To bring something to an end.", synonyms: ["finish", "end"] },
  { word: "Condense", partOfSpeech: "verb", definition: "To make something shorter.", synonyms: ["shorten", "abridge"] },
  { word: "Confront", partOfSpeech: "verb", definition: "To face a problem or person.", synonyms: ["face", "tackle"] },
  { word: "Construct", partOfSpeech: "verb", definition: "To build or make something.", synonyms: ["build", "create"] },
  { word: "Consult", partOfSpeech: "verb", definition: "To seek information or advice.", synonyms: ["ask", "check"] },
  { word: "Consume", partOfSpeech: "verb", definition: "To eat, drink, or use up.", synonyms: ["eat", "use"] },
  { word: "Contemplate", partOfSpeech: "verb", definition: "To look thoughtfully for a long time.", synonyms: ["ponder", "consider"] },
  { word: "Contribute", partOfSpeech: "verb", definition: "To give in order to help achieve.", synonyms: ["give", "help"] },
  { word: "Cultivate", partOfSpeech: "verb", definition: "To prepare and use land for crops.", synonyms: ["farm", "grow"] },
  { word: "Decipher", partOfSpeech: "verb", definition: "To succeed in understanding a code.", synonyms: ["decode", "solve"] },
  { word: "Declare", partOfSpeech: "verb", definition: "To say something officially.", synonyms: ["state", "announce"] },
  { word: "Decline", partOfSpeech: "verb", definition: "To become smaller or weaker.", synonyms: ["decrease", "fall"] },
  { word: "Dedicate", partOfSpeech: "verb", definition: "To devote time or effort to.", synonyms: ["devote", "commit"] },
  { word: "Define", partOfSpeech: "verb", definition: "To state the exact meaning of a word.", synonyms: ["explain", "describe"] },
  { word: "Demonstrate", partOfSpeech: "verb", definition: "To show clearly.", synonyms: ["show", "prove"] },
  { word: "Depict", partOfSpeech: "verb", definition: "To show in a drawing or painting.", synonyms: ["show", "portray"] },
  { word: "Design", partOfSpeech: "verb", definition: "To plan and make decisions about.", synonyms: ["plan", "create"] },
  { word: "Destroy", partOfSpeech: "verb", definition: "To damage something so it cannot be fixed.", synonyms: ["ruin", "wreck"] },
  { word: "Deter", partOfSpeech: "verb", definition: "To discourage someone from doing something.", synonyms: ["stop", "prevent"] },
  { word: "Devise", partOfSpeech: "verb", definition: "To plan or invent by careful thought.", synonyms: ["plan", "invent"] },
  { word: "Differentiate", partOfSpeech: "verb", definition: "To recognize what makes things different.", synonyms: ["distinguish", "separate"] },
  { word: "Diminish", partOfSpeech: "verb", definition: "To make or become less.", synonyms: ["decrease", "reduce"] },
  { word: "Discard", partOfSpeech: "verb", definition: "To get rid of someone or something.", synonyms: ["throw away", "reject"] },
  { word: "Disclose", partOfSpeech: "verb", definition: "To make secret information known.", synonyms: ["reveal", "tell"] },
  { word: "Disguise", partOfSpeech: "verb", definition: "To change appearance to hide identity.", synonyms: ["hide", "mask"] },
  { word: "Dismantle", partOfSpeech: "verb", definition: "To take a machine or structure apart.", synonyms: ["disassemble", "break down"] },
  { word: "Distinguish", partOfSpeech: "verb", definition: "To see the difference between things.", synonyms: ["tell apart", "differentiate"] },
  { word: "Distribute", partOfSpeech: "verb", definition: "To give shares of something.", synonyms: ["hand out", "share"] },
  { word: "Dominate", partOfSpeech: "verb", definition: "To have a commanding influence over.", synonyms: ["control", "rule"] },
  { word: "Draft", partOfSpeech: "verb", definition: "To prepare a preliminary version of a text.", synonyms: ["outline", "sketch"] },
  { word: "Drift", partOfSpeech: "verb", definition: "To be carried slowly by a current of air or water.", synonyms: ["float", "wander"] },
  { word: "Duplicate", partOfSpeech: "verb", definition: "To make an exact copy of.", synonyms: ["copy", "repeat"] },
  { word: "Dwell", partOfSpeech: "verb", definition: "To live in or at a specified place.", synonyms: ["live", "reside"] },
  { word: "Ebb", partOfSpeech: "verb", definition: "To move away from the land.", synonyms: ["recede", "retreat"] },
  { word: "Eclipse", partOfSpeech: "verb", definition: "To block the light from something.", synonyms: ["block", "obscure"] },
  { word: "Edit", partOfSpeech: "verb", definition: "To prepare text for publication.", synonyms: ["correct", "revise"] },
  { word: "Effect", partOfSpeech: "verb", definition: "To cause something to happen.", synonyms: ["cause", "produce"] },
  { word: "Elaborate", partOfSpeech: "verb", definition: "To develop or present in detail.", synonyms: ["expand", "explain"] },
  { word: "Elevate", partOfSpeech: "verb", definition: "To raise or lift up.", synonyms: ["lift", "raise"] },
  { word: "Eliminate", partOfSpeech: "verb", definition: "To completely remove or get rid of.", synonyms: ["remove", "stop"] },
  { word: "Emphasize", partOfSpeech: "verb", definition: "To give special importance to.", synonyms: ["stress", "highlight"] },
  { word: "Employ", partOfSpeech: "verb", definition: "To give work to someone.", synonyms: ["hire", "use"] },
  { word: "Enable", partOfSpeech: "verb", definition: "To give the means to do something.", synonyms: ["allow", "help"] },
  { word: "Enclose", partOfSpeech: "verb", definition: "To surround or close off on all sides.", synonyms: ["surround", "shut in"] },
  { word: "Encounter", partOfSpeech: "verb", definition: "To unexpectedly be faced with.", synonyms: ["meet", "face"] },
  { word: "Encourage", partOfSpeech: "verb", definition: "To give support or confidence.", synonyms: ["support", "inspire"] },
  { word: "Endure", partOfSpeech: "verb", definition: "To suffer patiently.", synonyms: ["last", "withstand"] },
  { word: "Enforce", partOfSpeech: "verb", definition: "To make sure a law is followed.", synonyms: ["apply", "impose"] },
  { word: "Engage", partOfSpeech: "verb", definition: "To participate or become involved in.", synonyms: ["join", "involve"] },
  { word: "Enhance", partOfSpeech: "verb", definition: "To intensify or improve the quality of.", synonyms: ["improve", "boost"] },
  { word: "Enlarge", partOfSpeech: "verb", definition: "To make something bigger.", synonyms: ["expand", "grow"] },
  { word: "Enlighten", partOfSpeech: "verb", definition: "To give someone greater knowledge.", synonyms: ["inform", "teach"] },
  { word: "Enrage", partOfSpeech: "verb", definition: "To make very angry.", synonyms: ["anger", "infuriate"] },
  { word: "Ensure", partOfSpeech: "verb", definition: "To make certain that something occurs.", synonyms: ["guarantee", "secure"] },
  { word: "Entertain", partOfSpeech: "verb", definition: "To provide amusement or enjoyment.", synonyms: ["amuse", "please"] },
  { word: "Entrust", partOfSpeech: "verb", definition: "To assign a responsibility to someone.", synonyms: ["assign", "trust"] },
  { word: "Enumerate", partOfSpeech: "verb", definition: "To mention a number of things one by one.", synonyms: ["list", "count"] },
  { word: "Envision", partOfSpeech: "verb", definition: "To imagine as a future possibility.", synonyms: ["imagine", "picture"] },
  { word: "Equip", partOfSpeech: "verb", definition: "To provide with needed items.", synonyms: ["prepare", "supply"] },
  { word: "Eradicate", partOfSpeech: "verb", definition: "To destroy completely.", synonyms: ["eliminate", "destroy"] },
  { word: "Erupt", partOfSpeech: "verb", definition: "To burst or break out suddenly.", synonyms: ["burst", "explode"] },
  { word: "Escape", partOfSpeech: "verb", definition: "To break free from confinement.", synonyms: ["flee", "get away"] },
  { word: "Establish", partOfSpeech: "verb", definition: "To set up on a firm basis.", synonyms: ["found", "start"] },
  { word: "Estimate", partOfSpeech: "verb", definition: "To roughly calculate a value.", synonyms: ["guess", "calculate"] },
  { word: "Evade", partOfSpeech: "verb", definition: "To escape or avoid.", synonyms: ["avoid", "shun"] },
  { word: "Evaluate", partOfSpeech: "verb", definition: "To form an idea of the value of.", synonyms: ["judge", "assess"] },
  { word: "Evaporate", partOfSpeech: "verb", definition: "To turn from liquid into vapor.", synonyms: ["vanish", "dry up"] },
  { word: "Exaggerate", partOfSpeech: "verb", definition: "To represent as better than it is.", synonyms: ["overstate", "inflate"] },
  { word: "Examine", partOfSpeech: "verb", definition: "To inspect in detail.", synonyms: ["study", "inspect"] },
  { word: "Exceed", partOfSpeech: "verb", definition: "To be greater in number or size.", synonyms: ["surpass", "pass"] },
  { word: "Excel", partOfSpeech: "verb", definition: "To be exceptionally good at something.", synonyms: ["shine", "succeed"] },
  { word: "Exchange", partOfSpeech: "verb", definition: "To give and receive.", synonyms: ["trade", "swap"] },
  { word: "Exclude", partOfSpeech: "verb", definition: "To leave out.", synonyms: ["omit", "ignore"] },
  { word: "Execute", partOfSpeech: "verb", definition: "To carry out or put into effect.", synonyms: ["perform", "do"] },
  { word: "Exhale", partOfSpeech: "verb", definition: "To breathe out.", synonyms: ["breathe out", "emit"] },
  { word: "Exhaust", partOfSpeech: "verb", definition: "To use up completely.", synonyms: ["drain", "tire"] },
  { word: "Exhibit", partOfSpeech: "verb", definition: "To publicly display.", synonyms: ["show", "display"] },
  { word: "Exist", partOfSpeech: "verb", definition: "To have objective reality or being.", synonyms: ["be", "live"] },
  { word: "Expand", partOfSpeech: "verb", definition: "To become larger or more extensive.", synonyms: ["grow", "enlarge"] },
  { word: "Expect", partOfSpeech: "verb", definition: "To regard something as likely to happen.", synonyms: ["anticipate", "predict"] },
  { word: "Expel", partOfSpeech: "verb", definition: "To force someone to leave a place.", synonyms: ["remove", "banish"] },
  { word: "Experiment", partOfSpeech: "verb", definition: "To perform a scientific procedure.", synonyms: ["test", "try"] },
  { word: "Explain", partOfSpeech: "verb", definition: "To make something clear.", synonyms: ["describe", "clarify"] },
  { word: "Explore", partOfSpeech: "verb", definition: "To travel in an unfamiliar area.", synonyms: ["investigate", "search"] },
  { word: "Expose", partOfSpeech: "verb", definition: "To make something visible by uncovering it.", synonyms: ["reveal", "uncover"] },
  { word: "Express", partOfSpeech: "verb", definition: "To convey a thought or feeling.", synonyms: ["state", "say"] },
  { word: "Extend", partOfSpeech: "verb", definition: "To cause to cover a larger area.", synonyms: ["stretch", "lengthen"] },
  { word: "Extract", partOfSpeech: "verb", definition: "To remove or take out by effort.", synonyms: ["remove", "pull"] },
  { word: "Fabricate", partOfSpeech: "verb", definition: "To invent or concoct, often with deceit.", synonyms: ["invent", "fake"] },
  { word: "Facilitate", partOfSpeech: "verb", definition: "To make an action or process easy.", synonyms: ["help", "ease"] },
  { word: "Fade", partOfSpeech: "verb", definition: "To gradually grow faint and disappear.", synonyms: ["dim", "vanish"] },
  { word: "Falter", partOfSpeech: "verb", definition: "To lose strength or momentum.", synonyms: ["stumble", "hesitate"] },
  { word: "Fascinate", partOfSpeech: "verb", definition: "To attract or interest intensely.", synonyms: ["charm", "captivate"] },
  { word: "Fathom", partOfSpeech: "verb", definition: "To understand after much thought.", synonyms: ["understand", "comprehend"] },
  { word: "Fear", partOfSpeech: "verb", definition: "To be afraid of.", synonyms: ["dread", "be scared of"] },
  { word: "Feature", partOfSpeech: "verb", definition: "To have as a prominent attribute.", synonyms: ["highlight", "show"] },
  { word: "Feed", partOfSpeech: "verb", definition: "To give food to.", synonyms: ["nourish", "provide for"] },
  { word: "Feel", partOfSpeech: "verb", definition: "To experience an emotion or sensation.", synonyms: ["sense", "experience"] },
  { word: "Feign", partOfSpeech: "verb", definition: "To pretend to be affected by.", synonyms: ["fake", "pretend"] },
  { word: "Fence", partOfSpeech: "verb", definition: "To surround with a fence.", synonyms: ["enclose", "boundary"] },
  { word: "Fetch", partOfSpeech: "verb", definition: "To go for and bring back.", synonyms: ["get", "bring"] },
  { word: "Fight", partOfSpeech: "verb", definition: "To take part in a violent struggle.", synonyms: ["battle", "struggle"] },
  { word: "Fill", partOfSpeech: "verb", definition: "To put someone or something into.", synonyms: ["stock", "pack"] },
  { word: "Find", partOfSpeech: "verb", definition: "To discover or perceive by chance.", synonyms: ["locate", "discover"] },
  { word: "Finish", partOfSpeech: "verb", definition: "To bring to an end.", synonyms: ["complete", "end"] },
  { word: "Fit", partOfSpeech: "verb", definition: "To be the right size or shape.", synonyms: ["match", "suit"] },
  { word: "Fix", partOfSpeech: "verb", definition: "To fasten something securely.", synonyms: ["repair", "mend"] },
  { word: "Flash", partOfSpeech: "verb", definition: "To shine with a sudden bright light.", synonyms: ["shimmer", "sparkle"] },
  { word: "Flatten", partOfSpeech: "verb", definition: "To make or become flat.", synonyms: ["level", "press"] },
  { word: "Flaunt", partOfSpeech: "verb", definition: "To display something ostentatiously.", synonyms: ["show off", "brag"] },
  { word: "Flee", partOfSpeech: "verb", definition: "To run away from a place.", synonyms: ["escape", "run"] },
  { word: "Flicker", partOfSpeech: "verb", definition: "To shine unsteadily.", synonyms: ["glimmer", "twinkle"] },
  { word: "Flinch", partOfSpeech: "verb", definition: "To make a quick nervous movement.", synonyms: ["cringe", "recoil"] },
  { word: "Fling", partOfSpeech: "verb", definition: "To throw or hurl forcefully.", synonyms: ["toss", "throw"] },
  { word: "Float", partOfSpeech: "verb", definition: "To rest or move on liquid without sinking.", synonyms: ["drift", "glide"] },
  { word: "Flock", partOfSpeech: "verb", definition: "To move or gather in a crowd.", synonyms: ["gather", "crowd"] },
  { word: "Flop", partOfSpeech: "verb", definition: "To fall or sit down heavily.", synonyms: ["slump", "collapse"] },
  { word: "Flourish", partOfSpeech: "verb", definition: "To grow or develop in a healthy way.", synonyms: ["thrive", "bloom"] },
  { word: "Flow", partOfSpeech: "verb", definition: "To move steadily and continuously.", synonyms: ["stream", "run"] },
  { word: "Fluctuate", partOfSpeech: "verb", definition: "To rise and fall irregularly.", synonyms: ["vary", "change"] },
  { word: "Flutter", partOfSpeech: "verb", definition: "To fly unsteadily or hover by flapping.", synonyms: ["flap", "waver"] },
  { word: "Fly", partOfSpeech: "verb", definition: "To move through the air using wings.", synonyms: ["soar", "wing"] },
  { word: "Focus", partOfSpeech: "verb", definition: "To adapt to the prevailing light.", synonyms: ["concentrate", "center"] },
  { word: "Fold", partOfSpeech: "verb", definition: "To bend something over itself.", synonyms: ["crease", "double"] },
  { word: "Follow", partOfSpeech: "verb", definition: "To go or come after a person.", synonyms: ["trail", "pursue"] },
  { word: "Fondle", partOfSpeech: "verb", definition: "To stroke or caress lovingly.", synonyms: ["pet", "stroke"] },
  { word: "Fool", partOfSpeech: "verb", definition: "To trick or deceive.", synonyms: ["deceive", "trick"] },
  { word: "Forbid", partOfSpeech: "verb", definition: "To refuse to allow something.", synonyms: ["prohibit", "ban"] },
  { word: "Force", partOfSpeech: "verb", definition: "To make someone do something.", synonyms: ["compel", "coerce"] },
  { word: "Forecast", partOfSpeech: "verb", definition: "To predict or estimate a future event.", synonyms: ["predict", "foretell"] },
  { word: "Foresee", partOfSpeech: "verb", definition: "To be aware of beforehand.", synonyms: ["predict", "anticipate"] },
  { word: "Forget", partOfSpeech: "verb", definition: "To fail to remember.", synonyms: ["omit", "overlook"] },
  { word: "Forgive", partOfSpeech: "verb", definition: "To stop feeling angry or resentful.", synonyms: ["pardon", "excuse"] },
  { word: "Formalize", partOfSpeech: "verb", definition: "To give something a definite form.", synonyms: ["standardize", "fix"] },
  { word: "Formulate", partOfSpeech: "verb", definition: "To create or prepare methodically.", synonyms: ["plan", "devise"] },
  { word: "Forsake", partOfSpeech: "verb", definition: "To abandon or give up.", synonyms: ["abandon", "leave"] },
  { word: "Fortify", partOfSpeech: "verb", definition: "To strengthen with defensive works.", synonyms: ["strengthen", "secure"] },
  { word: "Foster", partOfSpeech: "verb", definition: "To encourage or promote development.", synonyms: ["encourage", "nurture"] },
  { word: "Found", partOfSpeech: "verb", definition: "To establish or originate an institution.", synonyms: ["establish", "start"] },

  // --- NOUNS (341-500) ---
  { word: "Ambition", partOfSpeech: "noun", definition: "A strong wish to achieve something.", synonyms: ["goal", "dream"] },
  { word: "Journey", partOfSpeech: "noun", definition: "A long trip from one place to another.", synonyms: ["trip", "adventure", "voyage"] },
  { word: "Mystery", partOfSpeech: "noun", definition: "Something that is hard to explain or understand.", synonyms: ["secret", "puzzle"] },
  { word: "Courage", partOfSpeech: "noun", definition: "Being brave when you are afraid.", synonyms: ["bravery", "fearlessness"] },
  { word: "Triumph", partOfSpeech: "noun", definition: "A great victory or success.", synonyms: ["victory", "win"] },
  { word: "Zest", partOfSpeech: "noun", definition: "Great enthusiasm and energy.", synonyms: ["energy", "excitement"] },
  { word: "Aptitude", partOfSpeech: "noun", definition: "A natural ability to do something.", synonyms: ["talent", "skill"] },
  { word: "Artifact", partOfSpeech: "noun", definition: "An object made by a human being.", synonyms: ["relic", "antiquity"] },
  { word: "Atmosphere", partOfSpeech: "noun", definition: "The envelope of gases surrounding a planet.", synonyms: ["air", "sky"] },
  { word: "Authority", partOfSpeech: "noun", definition: "The power to give orders.", synonyms: ["power", "control"] },
  { word: "Barrier", partOfSpeech: "noun", definition: "A fence or other obstacle that prevents movement.", synonyms: ["obstacle", "fence"] },
  { word: "Benefit", partOfSpeech: "noun", definition: "An advantage or profit gained.", synonyms: ["advantage", "gain"] },
  { word: "Bias", partOfSpeech: "noun", definition: "Prejudice in favor of one thing.", synonyms: ["prejudice", "favoritism"] },
  { word: "Boundary", partOfSpeech: "noun", definition: "A line that marks the limits of an area.", synonyms: ["border", "limit"] },
  { word: "Capacity", partOfSpeech: "noun", definition: "The maximum amount something can contain.", synonyms: ["volume", "size"] },
  { word: "Category", partOfSpeech: "noun", definition: "A class or division of things.", synonyms: ["class", "group"] },
  { word: "Cause", partOfSpeech: "noun", definition: "A person or thing that gives rise to an action.", synonyms: ["reason", "source"] },
  { word: "Celebration", partOfSpeech: "noun", definition: "The action of marking an important event.", synonyms: ["party", "festival"] },
  { word: "Challenge", partOfSpeech: "noun", definition: "A task that tests someone's ability.", synonyms: ["test", "problem"] },
  { word: "Character", partOfSpeech: "noun", definition: "The mental qualities distinctive to an individual.", synonyms: ["personality", "nature"] },
  { word: "Circumstance", partOfSpeech: "noun", definition: "A fact or condition connected with an event.", synonyms: ["situation", "condition"] },
  { word: "Citizen", partOfSpeech: "noun", definition: "A legally recognized subject of a state.", synonyms: ["resident", "national"] },
  { word: "Clarity", partOfSpeech: "noun", definition: "The quality of being clear.", synonyms: ["clearness", "sharpness"] },
  { word: "Climate", partOfSpeech: "noun", definition: "The weather conditions prevailing in an area.", synonyms: ["weather", "conditions"] },
  { word: "Collection", partOfSpeech: "noun", definition: "The action of collecting something.", synonyms: ["group", "set"] },
  { word: "Combination", partOfSpeech: "noun", definition: "A joining of different elements.", synonyms: ["mixture", "blend"] },
  { word: "Comfort", partOfSpeech: "noun", definition: "A state of physical ease.", synonyms: ["ease", "relief"] },
  { word: "Community", partOfSpeech: "noun", definition: "A group of people living in the same place.", synonyms: ["society", "group"] },
  { word: "Compassion", partOfSpeech: "noun", definition: "Sympathetic pity for the sufferings of others.", synonyms: ["pity", "sympathy"] },
  { word: "Competition", partOfSpeech: "noun", definition: "The activity of competing.", synonyms: ["contest", "race"] },
  { word: "Component", partOfSpeech: "noun", definition: "A part or element of a larger whole.", synonyms: ["part", "piece"] },
  { word: "Concentration", partOfSpeech: "noun", definition: "The action of focusing one's attention.", synonyms: ["focus", "attention"] },
  { word: "Concept", partOfSpeech: "noun", definition: "An abstract idea.", synonyms: ["idea", "theory"] },
  { word: "Conclusion", partOfSpeech: "noun", definition: "The end or finish of an event.", synonyms: ["end", "finish"] },
  { word: "Condition", partOfSpeech: "noun", definition: "The state of something.", synonyms: ["state", "status"] },
  { word: "Confidence", partOfSpeech: "noun", definition: "A feeling of self-assurance.", synonyms: ["assurance", "trust"] },
  { word: "Conflict", partOfSpeech: "noun", definition: "A serious disagreement or argument.", synonyms: ["disagreement", "fight"] },
  { word: "Confusion", partOfSpeech: "noun", definition: "Lack of understanding.", synonyms: ["bewilderment", "chaos"] },
  { word: "Connection", partOfSpeech: "noun", definition: "A relationship in which things are linked.", synonyms: ["link", "bond"] },
  { word: "Consequence", partOfSpeech: "noun", definition: "A result or effect of an action.", synonyms: ["result", "effect"] },
  { word: "Conservation", partOfSpeech: "noun", definition: "Prevention of wasteful use of a resource.", synonyms: ["preservation", "protection"] },
  { word: "Construction", partOfSpeech: "noun", definition: "The building of something.", synonyms: ["building", "creation"] },
  { word: "Consumer", partOfSpeech: "noun", definition: "A person who purchases goods.", synonyms: ["buyer", "customer"] },
  { word: "Contact", partOfSpeech: "noun", definition: "Communication or meeting.", synonyms: ["communication", "touch"] },
  { word: "Content", partOfSpeech: "noun", definition: "The things that are held in something.", synonyms: ["substance", "matter"] },
  { word: "Context", partOfSpeech: "noun", definition: "The circumstances that form the setting for an event.", synonyms: ["setting", "background"] },
  { word: "Contribution", partOfSpeech: "noun", definition: "A gift or payment to a fund.", synonyms: ["gift", "donation"] },
  { word: "Control", partOfSpeech: "noun", definition: "The power to influence behavior.", synonyms: ["power", "authority"] },
  { word: "Conversation", partOfSpeech: "noun", definition: "The informal exchange of ideas by spoken words.", synonyms: ["chat", "talk"] },
  { word: "Cooperation", partOfSpeech: "noun", definition: "The process of working together.", synonyms: ["collaboration", "assistance"] },
  { word: "Council", partOfSpeech: "noun", definition: "An advisory body of people.", synonyms: ["committee", "board"] },
  { word: "Counsel", partOfSpeech: "noun", definition: "Advice, especially that given formally.", synonyms: ["advice", "guidance"] },
  { word: "County", partOfSpeech: "noun", definition: "A territorial division of some countries.", synonyms: ["region", "area"] },
  { word: "Couple", partOfSpeech: "noun", definition: "Two people or things.", synonyms: ["pair", "duo"] },
  { word: "Courage", partOfSpeech: "noun", definition: "The ability to do something that frightens one.", synonyms: ["bravery", "valor"] },
  { word: "Course", partOfSpeech: "noun", definition: "The route or direction followed.", synonyms: ["route", "path"] },
  { word: "Court", partOfSpeech: "noun", definition: "A tribunal presided over by a judge.", synonyms: ["tribunal", "bench"] },
  { word: "Cousin", partOfSpeech: "noun", definition: "A child of one's uncle or aunt.", synonyms: ["relative", "kin"] },
  { word: "Coverage", partOfSpeech: "noun", definition: "The extent to which something deals with something.", synonyms: ["scope", "extent"] },
  { word: "Craft", partOfSpeech: "noun", definition: "An activity involving skill in making things by hand.", synonyms: ["skill", "art"] },
  { word: "Creation", partOfSpeech: "noun", definition: "The action or process of bringing something into existence.", synonyms: ["making", "building"] },
  { word: "Creature", partOfSpeech: "noun", definition: "An animal, as distinct from a human being.", synonyms: ["animal", "beast"] },
  { word: "Credit", partOfSpeech: "noun", definition: "The ability of a customer to obtain goods before payment.", synonyms: ["trust", "recognition"] },
  { word: "Crew", partOfSpeech: "noun", definition: "A group of people who work on a ship or aircraft.", synonyms: ["team", "group"] },
  { word: "Crime", partOfSpeech: "noun", definition: "An action that constitutes an offense.", synonyms: ["offense", "wrongdoing"] },
  { word: "Criterion", partOfSpeech: "noun", definition: "A principle or standard by which something is judged.", synonyms: ["standard", "rule"] },
  { word: "Critic", partOfSpeech: "noun", definition: "A person who expresses a biased opinion.", synonyms: ["judge", "reviewer"] },
  { word: "Criticism", partOfSpeech: "noun", definition: "The expression of disapproval of someone.", synonyms: ["judgment", "review"] },
  { word: "Crop", partOfSpeech: "noun", definition: "A cultivated plant that is grown as food.", synonyms: ["harvest", "produce"] },
  { word: "Crowd", partOfSpeech: "noun", definition: "A large number of people gathered together.", synonyms: ["mob", "throng"] },
  { word: "Crown", partOfSpeech: "noun", definition: "A circular ornamental headdress worn by a monarch.", synonyms: ["coronet", "tiara"] },
  { word: "Crucial", partOfSpeech: "noun", definition: "Of great importance.", synonyms: ["critical", "essential"] },
  { word: "Cry", partOfSpeech: "noun", definition: "A loud inarticulate shout.", synonyms: ["shout", "scream"] },
  { word: "Crystal", partOfSpeech: "noun", definition: "A clear transparent mineral.", synonyms: ["quartz", "glass"] },
  { word: "Cube", partOfSpeech: "noun", definition: "A symmetrical three-dimensional shape.", synonyms: ["block", "die"] },
  { word: "Culture", partOfSpeech: "noun", definition: "The customs and beliefs of a particular group.", synonyms: ["customs", "tradition"] },
  { word: "Cup", partOfSpeech: "noun", definition: "A small bowl-shaped container.", synonyms: ["mug", "vessel"] },
  { word: "Curiosity", partOfSpeech: "noun", definition: "A strong desire to know something.", synonyms: ["inquisitiveness", "interest"] },
  { word: "Current", partOfSpeech: "noun", definition: "A body of water or air moving in a definite direction.", synonyms: ["flow", "stream"] },
  { word: "Curtain", partOfSpeech: "noun", definition: "A piece of material suspended as a screen.", synonyms: ["drape", "screen"] },
  { word: "Curve", partOfSpeech: "noun", definition: "A line or outline which gradually deviates from being straight.", synonyms: ["bend", "arc"] },
  { word: "Cushion", partOfSpeech: "noun", definition: "A soft bag of cloth stuffed with firm material.", synonyms: ["pillow", "pad"] },
  { word: "Custom", partOfSpeech: "noun", definition: "A traditional way of behaving.", synonyms: ["tradition", "habit"] },
  { word: "Customer", partOfSpeech: "noun", definition: "A person or organization that buys goods.", synonyms: ["buyer", "client"] },
  { word: "Cycle", partOfSpeech: "noun", definition: "A series of events that are regularly repeated.", synonyms: ["circle", "round"] },
  { word: "Daily", partOfSpeech: "noun", definition: "Done or occurring every day.", synonyms: ["every day", "regular"] },
  { word: "Damage", partOfSpeech: "noun", definition: "Physical harm caused to something.", synonyms: ["harm", "ruin"] },
  { word: "Dance", partOfSpeech: "noun", definition: "A series of movements that match the rhythm of music.", synonyms: ["movement", "ball"] },
  { word: "Danger", partOfSpeech: "noun", definition: "The possibility of suffering harm.", synonyms: ["peril", "risk"] },
  { word: "Darkness", partOfSpeech: "noun", definition: "The partial or total absence of light.", synonyms: ["shadow", "gloom"] },
  { word: "Data", partOfSpeech: "noun", definition: "Facts and statistics collected together.", synonyms: ["info", "figures"] },
  { word: "Date", partOfSpeech: "noun", definition: "The day of the month or year.", synonyms: ["day", "time"] },
  { word: "Daughter", partOfSpeech: "noun", definition: "A female child or person in relation to her parents.", synonyms: ["child", "girl"] },
  { word: "Dawn", partOfSpeech: "noun", definition: "The first appearance of light in the sky before sunrise.", synonyms: ["sunrise", "daybreak"] },
  { word: "Day", partOfSpeech: "noun", definition: "A period of twenty-four hours.", synonyms: ["period", "time"] },
  { word: "Dead", partOfSpeech: "noun", definition: "No longer alive.", synonyms: ["deceased", "gone"] },
  { word: "Deaf", partOfSpeech: "noun", definition: "Lacking the power of hearing.", synonyms: ["hearing-impaired", "unhearing"] },
  { word: "Deal", partOfSpeech: "noun", definition: "An agreement entered into by two or more parties.", synonyms: ["agreement", "pact"] },
  { word: "Dear", partOfSpeech: "noun", definition: "Regarded with deep affection.", synonyms: ["loved", "precious"] },
  { word: "Death", partOfSpeech: "noun", definition: "The action of dying.", synonyms: ["end", "demise"] },
  { word: "Debate", partOfSpeech: "noun", definition: "A formal discussion on a particular topic.", synonyms: ["discussion", "argument"] },
  { word: "Debt", partOfSpeech: "noun", definition: "Something that is owed or due.", synonyms: ["liability", "obligation"] },
  { word: "Decade", partOfSpeech: "noun", definition: "A period of ten years.", synonyms: ["period", "ten-year period"] },
  { word: "December", partOfSpeech: "noun", definition: "The twelfth month of the year.", synonyms: ["month", "winter"] },
  { word: "Decency", partOfSpeech: "noun", definition: "Behavior that conforms to accepted standards.", synonyms: ["propriety", "manners"] },
  { word: "Decision", partOfSpeech: "noun", definition: "A conclusion or resolution reached after consideration.", synonyms: ["choice", "judgment"] },
  { word: "Deck", partOfSpeech: "noun", definition: "A structure of planks or plates forming a floor.", synonyms: ["floor", "level"] },
  { word: "Decoration", partOfSpeech: "noun", definition: "The process of decorating something.", synonyms: ["ornament", "adornment"] },
  { word: "Decrease", partOfSpeech: "noun", definition: "The process of becoming smaller or fewer.", synonyms: ["fall", "reduction"] },
  { word: "Decree", partOfSpeech: "noun", definition: "An official order issued by a legal authority.", synonyms: ["order", "edict"] },
  { word: "Dedication", partOfSpeech: "noun", definition: "The quality of being dedicated or committed.", synonyms: ["commitment", "devotion"] },
  { word: "Deed", partOfSpeech: "noun", definition: "An action that is performed intentionally.", synonyms: ["action", "act"] },
  { word: "Deep", partOfSpeech: "noun", definition: "Extending far down from the top.", synonyms: ["bottomless", "low"] },
  { word: "Deer", partOfSpeech: "noun", definition: "A hoofed grazing or browsing animal.", synonyms: ["stag", "buck"] },
  { word: "Defeat", partOfSpeech: "noun", definition: "An instance of being defeated.", synonyms: ["loss", "failure"] },
  { word: "Defense", partOfSpeech: "noun", definition: "The action of defending from or resisting attack.", synonyms: ["protection", "guard"] },
  { word: "Deficit", partOfSpeech: "noun", definition: "The amount by which something is too small.", synonyms: ["shortfall", "loss"] },
  { word: "Degree", partOfSpeech: "noun", definition: "The amount or level of something.", synonyms: ["level", "amount"] },
  { word: "Delay", partOfSpeech: "noun", definition: "A period of time by which something is late.", synonyms: ["pause", "wait"] },
  { word: "Delegate", partOfSpeech: "noun", definition: "A person sent to represent others.", synonyms: ["representative", "envoy"] },
  { word: "Delight", partOfSpeech: "noun", definition: "Great pleasure.", synonyms: ["joy", "pleasure"] },
  { word: "Deliverance", partOfSpeech: "noun", definition: "The action of being rescued or set free.", synonyms: ["rescue", "release"] },
  { word: "Delivery", partOfSpeech: "noun", definition: "The action of delivering letters or packages.", synonyms: ["transfer", "shipping"] },
  { word: "Demand", partOfSpeech: "noun", definition: "An insistent and peremptory request.", synonyms: ["request", "call"] },
  { word: "Democracy", partOfSpeech: "noun", definition: "A system of government by the whole population.", synonyms: ["republic", "self-government"] },
  { word: "Demonstration", partOfSpeech: "noun", definition: "The action of showing how something is done.", synonyms: ["show", "display"] },
  { word: "Denial", partOfSpeech: "noun", definition: "The action of declaring something to be untrue.", synonyms: ["refusal", "rejection"] },
  { word: "Density", partOfSpeech: "noun", definition: "The degree of compactness of a substance.", synonyms: ["thickness", "solidity"] },
  { word: "Department", partOfSpeech: "noun", definition: "A division of a large organization.", synonyms: ["division", "branch"] },
  { word: "Departure", partOfSpeech: "noun", definition: "The action of leaving.", synonyms: ["leaving", "exit"] },
  { word: "Dependence", partOfSpeech: "noun", definition: "The state of relying on or being controlled by.", synonyms: ["reliance", "trust"] },
  { word: "Depiction", partOfSpeech: "noun", definition: "The action or result of depicting something.", synonyms: ["portrayal", "picture"] },
  { word: "Deposit", partOfSpeech: "noun", definition: "A sum of money placed in a bank account.", synonyms: ["payment", "down payment"] },
  { word: "Depression", partOfSpeech: "noun", definition: "Feelings of severe despondency and dejection.", synonyms: ["sadness", "gloom"] },
  { word: "Depth", partOfSpeech: "noun", definition: "The distance from the top to the bottom.", synonyms: ["deepness", "extent"] },
  { word: "Deputy", partOfSpeech: "noun", definition: "A person whose role is to help a more senior person.", synonyms: ["assistant", "aide"] },
  { word: "Derivation", partOfSpeech: "noun", definition: "The obtaining or developing of something.", synonyms: ["source", "origin"] },
  { word: "Description", partOfSpeech: "noun", definition: "A spoken or written representation.", synonyms: ["report", "account"] },
  { word: "Desert", partOfSpeech: "noun", definition: "A barren area of landscape.", synonyms: ["wasteland", "wilderness"] },
  { word: "Design", partOfSpeech: "noun", definition: "A plan or drawing produced to show the look.", synonyms: ["plan", "pattern"] },
  { word: "Designer", partOfSpeech: "noun", definition: "A person who plans the look or workings of something.", synonyms: ["creator", "architect"] },
  { word: "Desire", partOfSpeech: "noun", definition: "A strong feeling of wanting to have something.", synonyms: ["wish", "want"] },
  { word: "Desk", partOfSpeech: "noun", definition: "A piece of furniture with a flat surface for writing.", synonyms: ["table", "counter"] },
  { word: "Despair", partOfSpeech: "noun", definition: "The complete loss or absence of hope.", synonyms: ["hopelessness", "gloom"] },
  { word: "Dessert", partOfSpeech: "noun", definition: "The sweet course eaten at the end of a meal.", synonyms: ["pudding", "sweet"] },
  { word: "Destination", partOfSpeech: "noun", definition: "The place to which someone is going.", synonyms: ["goal", "target"] },
  { word: "Destiny", partOfSpeech: "noun", definition: "The events that will necessarily happen to a person.", synonyms: ["fate", "future"] },
  { word: "Destruction", partOfSpeech: "noun", definition: "The action or process of destroying something.", synonyms: ["ruin", "wreck"] },
  { word: "Detail", partOfSpeech: "noun", definition: "An individual fact or item.", synonyms: ["fact", "item"] },
  { word: "Detection", partOfSpeech: "noun", definition: "The action of identifying something.", synonyms: ["discovery", "finding"] },
  { word: "Detective", partOfSpeech: "noun", definition: "A person whose occupation is to investigate crimes.", synonyms: ["investigator", "sleuth"] },
  { word: "Determination", partOfSpeech: "noun", definition: "Firmness of purpose.", synonyms: ["resolve", "firmness"] },
  { word: "Developer", partOfSpeech: "noun", definition: "A person or thing that develops something.", synonyms: ["creator", "builder"] },
  { word: "Development", partOfSpeech: "noun", definition: "The process of developing or being developed.", synonyms: ["growth", "evolution"] },
  { word: "Device", partOfSpeech: "noun", definition: "A thing made or adapted for a particular purpose.", synonyms: ["tool", "gadget"] },
  { word: "Devil", partOfSpeech: "noun", definition: "An evil spirit or being.", synonyms: ["demon", "spirit"] },
  { word: "Devotion", partOfSpeech: "noun", definition: "Love, loyalty, or enthusiasm for a person.", synonyms: ["loyalty", "love"] },
  { word: "Diagram", partOfSpeech: "noun", definition: "A simplified drawing showing the appearance.", synonyms: ["chart", "sketch"] },
  { word: "Dialect", partOfSpeech: "noun", definition: "A particular form of a language.", synonyms: ["accent", "vernacular"] },
  { word: "Dialogue", partOfSpeech: "noun", definition: "Conversation between two or more people.", synonyms: ["talk", "conversation"] },
  { word: "Diamond", partOfSpeech: "noun", definition: "A precious stone consisting of a clear crystal.", synonyms: ["gem", "jewel"] },
  { word: "Diary", partOfSpeech: "noun", definition: "A book in which one keeps a daily record of events.", synonyms: ["journal", "log"] },
  { word: "Dictionary", partOfSpeech: "noun", definition: "A book that lists the words of a language.", synonyms: ["lexicon", "wordbook"] },
  { word: "Diet", partOfSpeech: "noun", definition: "The kinds of food that a person habitually eats.", synonyms: ["food", "nutrition"] },
  { word: "Difference", partOfSpeech: "noun", definition: "A point or way in which things are not the same.", synonyms: ["disparity", "variation"] },
  { word: "Difficulty", partOfSpeech: "noun", definition: "The state or quality of being hard to do.", synonyms: ["hardship", "trouble"] },
  { word: "Dignity", partOfSpeech: "noun", definition: "The state or quality of being worthy of respect.", synonyms: ["respect", "honor"] },
  { word: "Dilemma", partOfSpeech: "noun", definition: "A situation in which a difficult choice has to be made.", synonyms: ["problem", "puzzle"] },
  { word: "Dimension", partOfSpeech: "noun", definition: "A measurable extent of some kind.", synonyms: ["size", "extent"] },
  { word: "Dinner", partOfSpeech: "noun", definition: "The main meal of the day.", synonyms: ["meal", "supper"] },
  { word: "Dinosaur", partOfSpeech: "noun", definition: "An extinct reptile of the Mesozoic era.", synonyms: ["reptile", "prehistoric animal"] },
  { word: "Direction", partOfSpeech: "noun", definition: "A course along which someone or something moves.", synonyms: ["way", "route"] },
  { word: "Director", partOfSpeech: "noun", definition: "A person who is in charge of an activity.", synonyms: ["manager", "boss"] },
  { word: "Directory", partOfSpeech: "noun", definition: "A book or website listing individuals.", synonyms: ["listing", "index"] },
  { word: "Dirt", partOfSpeech: "noun", definition: "A substance, such as mud or dust.", synonyms: ["grime", "filth"] },
  { word: "Disability", partOfSpeech: "noun", definition: "A physical or mental condition that limits a person.", synonyms: ["impairment", "condition"] },
  { word: "Disadvantage", partOfSpeech: "noun", definition: "An unfavorable circumstance.", synonyms: ["drawback", "handicap"] },
  { word: "Disagreement", partOfSpeech: "noun", definition: "Lack of consensus or approval.", synonyms: ["conflict", "argument"] },
  { word: "Disappearance", partOfSpeech: "noun", definition: "An instance of someone being lost.", synonyms: ["vanishing", "loss"] },
  { word: "Disaster", partOfSpeech: "noun", definition: "A sudden accident or a natural catastrophe.", synonyms: ["catastrophe", "calamity"] },
  { word: "Disc", partOfSpeech: "noun", definition: "A flat, thin, circular object.", synonyms: ["circle", "plate"] },
  { word: "Discharge", partOfSpeech: "noun", definition: "The action of releasing someone from a duty.", synonyms: ["release", "firing"] },
  { word: "Discipline", partOfSpeech: "noun", definition: "The practice of training people to obey rules.", synonyms: ["order", "control"] },
  { word: "Disclosure", partOfSpeech: "noun", definition: "The action of making new or secret info known.", synonyms: ["revelation", "report"] },
  { word: "Discomfort", partOfSpeech: "noun", definition: "Slight pain or worry.", synonyms: ["unease", "pain"] },
  { word: "Discovery", partOfSpeech: "noun", definition: "The action of finding something.", synonyms: ["finding", "detection"] },
  { word: "Discretion", partOfSpeech: "noun", definition: "The quality of behaving in a way to avoid offense.", synonyms: ["care", "caution"] },
  { word: "Discussion", partOfSpeech: "noun", definition: "The action of talking about something.", synonyms: ["talk", "debate"] },
  { word: "Disease", partOfSpeech: "noun", definition: "A disorder of structure or function in a human.", synonyms: ["illness", "sickness"] },
  { word: "Disguise", partOfSpeech: "noun", definition: "A means of altering one's appearance.", synonyms: ["mask", "cover"] },
  { word: "Dish", partOfSpeech: "noun", definition: "A shallow container used for cooking or serving.", synonyms: ["plate", "bowl"] },
  { word: "Dislike", partOfSpeech: "noun", definition: "A feeling of distaste or hostility.", synonyms: ["distaste", "hatred"] },
  { word: "Dismissal", partOfSpeech: "noun", definition: "The act of ordering someone to leave.", synonyms: ["firing", "removal"] },
  { word: "Disorder", partOfSpeech: "noun", definition: "A state of confusion.", synonyms: ["chaos", "mess"] },
  { word: "Display", partOfSpeech: "noun", definition: "A collection of objects arranged for public viewing.", synonyms: ["show", "exhibition"] },
  { word: "Dispute", partOfSpeech: "noun", definition: "A disagreement, argument, or debate.", synonyms: ["argument", "quarrel"] },
  { word: "Distance", partOfSpeech: "noun", definition: "An amount of space between two things.", synonyms: ["gap", "extent"] },
  { word: "Distinction", partOfSpeech: "noun", definition: "A difference or contrast between things.", synonyms: ["difference", "contrast"] },
  { word: "Distraction", partOfSpeech: "noun", definition: "A thing that prevents someone from giving full attention.", synonyms: ["diversion", "interruption"] },
  { word: "Distress", partOfSpeech: "noun", definition: "Extreme anxiety, sorrow, or pain.", synonyms: ["anguish", "suffering"] },
  { word: "Distribution", partOfSpeech: "noun", definition: "The action of sharing something out.", synonyms: ["sharing", "allocation"] },
  { word: "District", partOfSpeech: "noun", definition: "An area of a country or city.", synonyms: ["area", "region"] },
  { word: "Distrust", partOfSpeech: "noun", definition: "The feeling that someone is not honest.", synonyms: ["suspicion", "doubt"] },
  { word: "Disturbance", partOfSpeech: "noun", definition: "The interruption of a settled condition.", synonyms: ["interruption", "trouble"] },
  { word: "Dive", partOfSpeech: "noun", definition: "A plunge headfirst into water.", synonyms: ["plunge", "jump"] },
  { word: "Diversity", partOfSpeech: "noun", definition: "The state of being diverse.", synonyms: ["variety", "range"] },
  { word: "Division", partOfSpeech: "noun", definition: "The action of separating something into parts.", synonyms: ["separation", "split"] },
  { word: "Divorce", partOfSpeech: "noun", definition: "The legal dissolution of a marriage.", synonyms: ["split", "separation"] },
  { word: "Doctor", partOfSpeech: "noun", definition: "A qualified practitioner of medicine.", synonyms: ["physician", "medic"] },
  { word: "Document", partOfSpeech: "noun", definition: "A piece of written matter.", synonyms: ["paper", "record"] },
  { word: "Dog", partOfSpeech: "noun", definition: "A domesticated carnivorous mammal.", synonyms: ["hound", "canine"] },
  { word: "Dollar", partOfSpeech: "noun", definition: "The basic monetary unit of the US.", synonyms: ["buck", "currency"] },
  { word: "Domain", partOfSpeech: "noun", definition: "An area of territory owned by a ruler.", synonyms: ["territory", "field"] },
  { word: "Dominance", partOfSpeech: "noun", definition: "Power and influence over others.", synonyms: ["control", "rule"] },
  { word: "Donation", partOfSpeech: "noun", definition: "Something that is given to a charity.", synonyms: ["gift", "contribution"] },
  { word: "Door", partOfSpeech: "noun", definition: "A hinged barrier used to close an opening.", synonyms: ["portal", "entryway"] },
  { word: "Dose", partOfSpeech: "noun", definition: "A quantity of a medicine taken at one time.", synonyms: ["amount", "measure"] },
  { word: "Dot", partOfSpeech: "noun", definition: "A small round mark or spot.", synonyms: ["spot", "point"] },
  { word: "Double", partOfSpeech: "noun", definition: "A person or thing that looks exactly like another.", synonyms: ["twin", "duplicate"] },
  { word: "Doubt", partOfSpeech: "noun", definition: "A feeling of uncertainty or lack of conviction.", synonyms: ["uncertainty", "hesitation"] },
  { word: "Down", partOfSpeech: "noun", definition: "Fine soft feathers of birds.", synonyms: ["feathers", "fluff"] },
  { word: "Draft", partOfSpeech: "noun", definition: "A preliminary version of a piece of writing.", synonyms: ["outline", "sketch"] },
  { word: "Dragon", partOfSpeech: "noun", definition: "A mythical monster like a giant reptile.", synonyms: ["serpent", "monster"] },
  { word: "Drama", partOfSpeech: "noun", definition: "A play for theater, radio, or television.", synonyms: ["play", "show"] },
  { word: "Drawer", partOfSpeech: "noun", definition: "A boxlike storage compartment.", synonyms: ["compartment", "shelf"] },
  { word: "Drawing", partOfSpeech: "noun", definition: "A picture or diagram made with a pencil.", synonyms: ["picture", "sketch"] },
  { word: "Dream", partOfSpeech: "noun", definition: "A series of thoughts occurring in a person's sleep.", synonyms: ["vision", "fantasy"] },
  { word: "Dress", partOfSpeech: "noun", definition: "A one-piece garment for a woman or girl.", synonyms: ["gown", "frock"] },
  { word: "Drift", partOfSpeech: "noun", definition: "The continuous slow movement from one place to another.", synonyms: ["flow", "current"] },
  { word: "Drill", partOfSpeech: "noun", definition: "A hand tool or machine with a rotating cutting tip.", synonyms: ["tool", "exercise"] },
  { word: "Drink", partOfSpeech: "noun", definition: "A liquid that can be swallowed.", synonyms: ["beverage", "liquid"] },
  { word: "Drive", partOfSpeech: "noun", definition: "A trip or journey in a car.", synonyms: ["trip", "journey"] },
  { word: "Driver", partOfSpeech: "noun", definition: "A person who drives a vehicle.", synonyms: ["operator", "pilot"] },
  { word: "Drop", partOfSpeech: "noun", definition: "A small round mass of liquid.", synonyms: ["bead", "globule"] },
  { word: "Drought", partOfSpeech: "noun", definition: "A prolonged period of abnormally low rainfall.", synonyms: ["dry spell", "aridness"] },
  { word: "Drug", partOfSpeech: "noun", definition: "A medicine or other substance.", synonyms: ["medicine", "remedy"] },
  { word: "Drum", partOfSpeech: "noun", definition: "A percussion instrument.", synonyms: ["snare", "bongo"] },
  { word: "Dryer", partOfSpeech: "noun", definition: "A machine or device for drying something.", synonyms: ["drying machine", "airer"] },
  { word: "Dual", partOfSpeech: "noun", definition: "Consisting of two parts.", synonyms: ["double", "twin"] },
  { word: "Duck", partOfSpeech: "noun", definition: "A waterbird with a broad blunt bill.", synonyms: ["mallard", "teal"] },
  { word: "Dude", partOfSpeech: "noun", definition: "A man; a guy.", synonyms: ["man", "guy"] },
  { word: "Due", partOfSpeech: "noun", definition: "Expected at or planned for at a certain time.", synonyms: ["owed", "expected"] },
  { word: "Duke", partOfSpeech: "noun", definition: "A male holding the highest hereditary title.", synonyms: ["nobleman", "lord"] },
  { word: "Dump", partOfSpeech: "noun", definition: "A site for depositing garbage.", synonyms: ["tip", "junkyard"] },
  { word: "Duo", partOfSpeech: "noun", definition: "A pair of people or things.", synonyms: ["pair", "couple"] },
  { word: "Duplication", partOfSpeech: "noun", definition: "The action of duplicating something.", synonyms: ["copying", "repetition"] },
  { word: "Durability", partOfSpeech: "noun", definition: "The ability to withstand wear.", synonyms: ["strength", "toughness"] },
  { word: "Duration", partOfSpeech: "noun", definition: "The time during which something continues.", synonyms: ["period", "length"] },
  { word: "Dusk", partOfSpeech: "noun", definition: "The darker stage of twilight.", synonyms: ["twilight", "sunset"] },
  { word: "Dust", partOfSpeech: "noun", definition: "Fine, dry powder consisting of tiny particles.", synonyms: ["grime", "dirt"] },
  { word: "Duty", partOfSpeech: "noun", definition: "A moral or legal obligation.", synonyms: ["obligation", "responsibility"] }
];

const evaluationSchema: Schema = {
  type: Type.OBJECT,
  properties: {
    score: { type: Type.INTEGER, description: "Rating from 1 to 5 stars" },
    feedback: { type: Type.STRING, description: "A friendly, encouraging note about the sentence." },
    correction: { type: Type.STRING, description: "A grammatically corrected version of the sentence, if needed. Otherwise, empty string." },
    betterExamples: { 
      type: Type.ARRAY, 
      items: { type: Type.STRING },
      description: "Exactly two creative and high-quality example sentences using the target word." 
    }
  },
  required: ["score", "feedback", "betterExamples"],
};

export const getWordBatch = async (count: number): Promise<WordChallenge[]> => {
  const array = [...WORD_BANK];
  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [array[i], array[j]] = [array[j], array[i]];
  }
  return array.slice(0, count);
};

export const createCustomBatch = async (words: string[]): Promise<WordChallenge[]> => {
  if (words.length === 0) return [];
  const cleanWords = words.map(w => w.trim()).filter(w => w.length > 0 && w.length < 30).slice(0, 50);
  if (cleanWords.length === 0) return [];

  const schema: Schema = {
    type: Type.ARRAY,
    items: {
      type: Type.OBJECT,
      properties: {
        word: { type: Type.STRING },
        partOfSpeech: { type: Type.STRING },
        definition: { type: Type.STRING },
        synonyms: { type: Type.ARRAY, items: { type: Type.STRING } },
      },
      required: ["word", "partOfSpeech", "definition", "synonyms"],
    }
  };

  try {
    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: `Provide dictionary data for these words: ${JSON.stringify(cleanWords)}`,
      config: {
        systemInstruction: "You are a friendly junior dictionary for 10-12 year olds. Always provide simple definitions and helpful synonyms. Output strictly valid JSON.",
        responseMimeType: "application/json",
        responseSchema: schema,
        temperature: 0.1,
        thinkingConfig: { thinkingBudget: 0 }
      },
    });

    const text = response.text;
    if (!text) throw new Error("No response from AI");
    return JSON.parse(text) as WordChallenge[];
  } catch (error) {
    console.error("Custom batch generation failed", error);
    return cleanWords.map(w => ({
      word: w,
      partOfSpeech: "word",
      definition: "Let's practice writing a sentence with this word!",
      synonyms: []
    }));
  }
};

export const evaluateSentence = async (word: string, sentence: string): Promise<EvaluationResult> => {
  try {
    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: `Word: "${word}"\nStudent's Sentence: "${sentence}"`,
      config: {
        systemInstruction: `You are a supportive and professional English writing coach for students aged 10-12. 
        Your goal is to provide constructive feedback on their use of vocabulary and grammar.
        RULES:
        1. Always be encouraging.
        2. Score from 1 to 5 (5 is perfect).
        3. ALWAYS provide exactly two 'betterExamples' showing creative use of the word.
        4. If there is a grammatical error, provide a 'correction'.
        5. If the sentence is perfect, celebrate their creativity in 'feedback'.
        6. Do not refuse to answer. If the sentence is confusing, give a 1-star and explain why nicely.`,
        responseMimeType: "application/json",
        responseSchema: evaluationSchema,
        temperature: 0.7,
        thinkingConfig: { thinkingBudget: 0 }
      },
    });

    const text = response.text;
    if (!text) throw new Error("Empty response");
    
    const result = JSON.parse(text) as EvaluationResult;
    
    if (!result.betterExamples || result.betterExamples.length === 0) {
      result.betterExamples = [
        `He used the word ${word} in a sentence today.`,
        `The teacher was happy to see the word ${word} used correctly.`
      ];
    }
    
    return result;
  } catch (error) {
    console.error("Evaluation error:", error);
    return {
      score: 3,
      feedback: "I received your sentence! My connection is a bit slow right now, but keep up the great effort!",
      betterExamples: [
        `The ${word} child went to the park.`,
        `We should always try to be ${word} in our work.`
      ]
    };
  }
};